export const INCREMENT_AGE = "INCREMENT_AGE";
export const FETCH_CAT_REQUEST = "FETCH_CAT_REQUEST";
export const FETCH_CAT_SUCCESS = "FETCH_CAT_SUCCESS";
export const FETCH_CAT_FAILURE = "FETCH_CAT_FAILURE";
