export const FETCH_CAT_REQUEST = "FETCH_CAT_REQUEST";
export const FETCH_CAT_SUCCESS = "FETCH_CAT_SUCCESS";
export const FETCH_CAT_FAILURE = "FETCH_CAT_FAILURE";
export const UPDATE_CAT_REQUEST = "UPDATE_CAT_REQUEST";
export const UPDATE_CAT_SUCCESS = "UPDATE_CAT_SUCCESS";
export const UPDATE_CAT_FAILURE = "UPDATE_CAT_FAILURE";
export const NEW_CAT_REQUEST = "NEW_CAT_REQUEST";
